# docker-compose.yml
version: '3.8'

services:
  tactical-server:
    build: .
    ports:
      - "8765:8765"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    command: python server.py --host 0.0.0.0 --port 8765
